apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-nginx-pocho
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: Pod
metadata:
  name: nginx-pocho
spec:
  containers:
    - name: nginx-pocho
      image: nginx:latest
      resources:
        requests:
          memory: "128Mi"
          cpu: "500m"
        limits:
          memory: "256Mi"
          cpu: "500m"
      volumeMounts:
        - name: persistent-storage
          mountPath: /usr/share/nginx/html
  volumes:
    - name: persistent-storage
      persistentVolumeClaim:
        claimName: pvc-nginx-pocho
